### ISSUE TITLE
Вопросы

### ISSUE THREAD

**Issue by kuk** [natasha/nerus#2]
Очень интересная инициатива. Сейчас для внутренних проектов изучаю современные методы для тегирования. Плюс, давно хочу заменить CRF-модель в Наташе на что-то с нормальным качеством. Не зная об этом репозитории даже попробовал сделать то же самое, тоже на текстах с Ленты, но с Томита-парсером (только PER) и с Pullenti. Вопросы, предложение:
1. Есть какая-то инструкция, как обработать Ленту https://texterra.ispras.ru/ и http://lang.org.ua/en/models/#anchor3 ?
2. Пишут, что deepmipt/ner устарел, надо юзать https://github.com/deepmipt/DeepPavlov . На https://demo.ipavlov.ai/ у них качество лучше, чем deepmipt/ner. Возможно, как раз там используется DeepPavlov
3. Мне кажется, полезно выкладывать сырые результаты по каждому инструменту: отдельно результаты texterra, отдельно deepmipt. Также хорошо бы зафиксировать, выложить и исходные тексты статей. Тогда можно перегенирировать финальную разметку, если поменяется один из инструментов.
4. Не думал, о том, чтобы прогнать предложения с неоднозначной разметкой через Толоку? Предложить асессорам не "рисовать" разметку, а дать две кнопки "правильная разметка", "неправильная разметка".
5. Нет проблем с выкладкой данных в виде релизов? Может быть, использовать S3?
6. Есть вот такая ссылка с русскими новостными текстами https://github.com/buriy/russian-nlp-datasets/releases , можно тоже обработать, сам не смотрел
7. Хотелось бы иметь пайплайн, в котором зафиксирована логика получения датасета: как запускается texterra, deepmipt, natasha, как результаты объединяются.
8. Хорошо бы в результаты разметки складывать структурированное представление. Например, не `"text": "Дмитрием Светозаровым"`, а `"first": "Дмитрий", "last": "Светозаров"`
9. Не очень удобно распаковывать архив из 100 000+ файлов, подтормаживает файловая система. Может быть использовать jsonl?
10. Может перенести репозиторий в github.com/natasha?

**Comment by dveselov** [comment]
Привет,
1. Нужно скачать [бинарный пакет Texterra](https://texterra.ispras.ru/products) и заиспользовать их [клиентскую библиотеку](https://github.com/ispras/texterra-py). Моделька с lang.org.ua использует MITIE, у них в репо есть пример [как использовать NER](https://github.com/mit-nlp/MITIE/blob/master/examples/python/ner.py)
2. Не видел, спасибо
3. Иногда там откровенный бред получается (когда не отсекаются теги без согласования с другими аннотаторами), но вообще можно, да
4. А зачем? Для этого используется кол-во согласований для каждого тега
5. Вроде бы, там ограничение в 1GB на файл, пока что хватает
6. Не видел, спасибо
7. По идее, все скрипты-аннотаторы будут лежать в [своем репозитории](https://github.com/bureaucratic-labs/amnesia-annotators), но сейчас этого нету, да и код там несложный в большинстве случаев. Сама система для разметки - это [amnesia-base](https://github.com/bureaucratic-labs/amnesia-base), там всё крутится вокруг HTTP REST API в котором можно взять текст на разметку, записать теги/спаны, взять ещё текст и т.д. Документации по ней тоже нету, но есть код - можно мосмотреть на [структуру базы](https://github.com/bureaucratic-labs/amnesia-base/blob/master/amnesia/models/corpus.py) или на [скрипт для экспорта в json](https://github.com/bureaucratic-labs/amnesia-base/blob/master/amnesia/manage.py#L46).
8. Если я правильно помню, так умеет только Natasha и Pullenti - как тогда поступать с остальными?
9. Да, можно
10. Пока что в таком экспериментальном виде полежит тут, а потом можно и туда

**Comment by kuk** [comment]
-4. Чтобы в разметку попали правильные теги без согласования. Может же такое быть что, например, Texterra поставила правильный тег, но все остальные системы тег не поставили. Есть опасение, что если брать только теги с согласованием, разметка будет упрощённой, будет пропускать сложные случаи.

-7. Если смелое предложение: нет ли желания использовать https://github.com/natasha/ipyannotate для разметки, а результаты хранить в файликах, а не базе данных ))  

-8. В Pullenti есть такая вещь как слоты, это список пар `[("first", "павел"), ("last", "гусев")]`. Для всех остальных можно писать пустой список. Просто если так окажется, что среди согласований для тега есть Pullenti, можно для него выдать и структурированое представление.

**Comment by kuk** [comment]
> Не зная об этом репозитории даже попробовал сделать то же самое, тоже на текстах с Ленты, но с Томита-парсером (только PER) и с Pullenti.

Я закончил со своими экспериментами, получился неплохой результат. В целом тоже самое что в этом репозитории, плюс:
1. Дополнительные аннтаторы: Pullenti, Tomita, Deeppavlov (не deeppavlov/ner)
2. Аннотаторы оформлены в виде докер-контейнеров. Пересчёт по кнопке.
3. Оценка качества полученной разметки. Я беру данные https://github.com/dialogue-evaluation/factRuEval-2016 (~200 текстов) в http://labinform.ru/pub/named_entities/descr_ne.htm (1000 текстов), размечаю их Pullenti, Deeppavlov, Texterra, Tomita, MITIE и Natasha, делаю смесь и смотрю разницу с эталонной разметкой.
4. Немного другой формат данных, но тоже json. Я сохраняю не только финальную разметку, но результаты работы отдельных аннотаторов.

В ближайшие 1-2 месяца хочу оформить результаты в виде пакета. Можем ли мы договориться, что я оформлю большой пулл-реквест к этому репозиторию, если ты его примешь, мы перенесём репозиторий в github/natasha?

**Comment by dveselov** [comment]
Отличные новости, я только за.

**Comment by kuk** [comment]
Продолжение https://github.com/bureaucratic-labs/russian-ner-corpus/pull/3
