### ISSUE TITLE
Licensing NERUS with a more open license

### ISSUE THREAD

**Issue by buriy** [natasha/nerus#6]
Hi all,

Could you consider re-releasing NERUS without a Non-Commercial clause?
The NC license of the dataset makes it harder to use the dataset to build models used widely (with a license allowing public use e. g. MIT license).
Or maybe we can build another similar corpus with that purpose in mind?

I think due to that news articles in Russia can be re-distributed freely (with links to authors), you can allow commercial usage, only with an additional clause that the articles included in the corpus are copyrighted by their authors and can't be used for reproduction, printing or copying of these articles without an agreement from their authors (this restriction wouldn't disable fair use -- e.g. educational use, scientific use, quotation).

Some other databases already did so, for example, Russian Superglue dataset authors claim in https://russiansuperglue.com/faq/ :
"The primary SuperGLUE tasks are built on existing datasets or derived from them. In Russian version we have created the equivalents from scratch. All our datasets are published by MIT License."
Despite using quotes from different copyrighted texts.

**Comment by kuk** [comment]
https://github.com/natasha/nerus/commit/ed6e5dfd891b2ec9fe3d5901465bbcb08116a37d
Changed to MIT as in other Natasha repos
